Repository Homeservenow/serverless-aws-handler, pull requests merged in 2020-07, with the labels that each got.

#7 chore: added npmignore
  .npmignore
Labels: enhancement

#6 feat: changed default error options to 400 - 598
  src/enum.ts
  src/http.handler.ts
Labels: bug, enhancement

#9 feat: updated readme
  readme.md
Labels: documentation

#10 HSND-383 Refactor/handler types
  LICENCE
  package.json
  readme.md
  src/decorator.ts
  src/http.error.handler.ts
  src/http.handler.ts
  src/http.response.handler.ts
  src/index.ts
  src/interfaces.ts
  src/logging.handler.ts
  src/test/events/api.gateway.event.ts
  src/test/events/index.ts
  src/test/http.handler.spec.ts
  src/test/logging.handler.spec.ts
  src/utils/index.ts
  src/utils/json.parse.ts
  tsconfig.json
Labels: bug, documentation, enhancement

#14 Refactor/payload to body
  package.json
  readme.md
  src/http.handler.ts
  src/interfaces.ts
  src/test/http.handler.spec.ts
Labels: documentation

#15 feat: added validation error exception
  src/decorator.ts
  src/exceptions/index.ts
  src/exceptions/validation.exception.ts
  src/http.handler.options.ts
  src/http.handler.ts
  src/interfaces.ts
  src/logging.handler.ts
  src/test/decorator.spec.ts
  src/test/exceptions.spec.ts
  src/test/http.handler.spec.ts
Labels: enhancement

#16 Feature/flow chart
  .npmignore
  flow-chart.png
  readme.md
Labels: documentation

#19 fix: corrected status code
  src/enums/http.status.code.ts
  src/test/http.handler.spec.ts
Labels: bug
